# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b3e0b93e7013652a027f7aadc152b1012f49a04c51b1574735a479201820858ea3a45bdf9c5dd62982b0b9d96abdbe82e155803eb5b1d0c15d980d659e746c7

test:
  secret_key_base: 089977faccde66fb8a45596743d262fc8e2f5b5f78009480c60d391deefb23a16186c8e78af12abc0dc3d651bada0c256d91e9f29ea33f183d8f927c8dc280c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
